### ISSUE TITLE
Wireframe census tract walkthrough between 2010 and 2020 Census Deccenial Data

### ISSUE THREAD

**Issue by ddil-projects** [de-data-lab/census-tract-redistricting#1]
1. Note that the **decennial data** is the only currently accessible data for any conversion. ACS and census tract level data will be released in March 2020. 
2. 218 census tracts were redistricted into 267 census tracts in the newest census release. 
3. The output for this, is a single list with two columns, one for the old census tract and one for the new census tract label respectively. 
4. The script is going to be necessary regardless, because it can be then applied to any other state or version of the redistricting (e.g. when re-pooling data).

**Comment by nsunami** [comment]
Here are some resources that may be useful:


1. [Census Bureau's Press Kit](https://www.census.gov/newsroom/press-kits/2021/2020-census-redistricting.html)
2. [Census Bureau's Guide](https://www.census.gov/programs-surveys/decennial-census/about/rdo/summary-files.html#P1)
3. [Carolina Demography's Guides](https://www.ncdemography.org/2021/08/11/census-2020-story-recipe-how-to-find-and-explore-census-data/) and [GitHub repo](https://github.com/mcclatchy-southeast/census2020) mentioned in the guide (NC only)

**Comment by nsunami** [comment]
Is are these [redistricting files](https://www.census.gov/geographies/reference-files/time-series/geo/relationship-files.html) relevant here?

Data for DE are available [here](https://www2.census.gov/geo/docs/maps-data/data/rel2020/tract/tab20_tract20_tract10_st10.txt) ([documentation](https://www2.census.gov/geo/pdfs/maps-data/data/rel2020/tract/explanation_tab20_tract20_tract10.pdf))

**Comment by Gastastrophe** [comment]
I believe this was completed some time ago
